name: Build iOS App

on:
  push:
    branches: [main, payment] # Se déclenche quand vous poussez sur main ou master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - name: Install Dependencies
        run: flutter pub get

      - name: Configurer les clés Apple API
        env:
          KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_KEY_CONTENT }}
        run: |
          mkdir -p ~/.appstoreconnect/private_keys
          echo "$KEY_CONTENT" > ~/.appstoreconnect/private_keys/AuthKey_$KEY_ID.p8

      - name: Install Pods
        run: |
          cd ios
          pod install

      - name: Créer le fichier ExportOptions automatiquement
        run: |
          cat <<EOF > ios/ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>destination</key>
              <string>export</string>
              <key>method</key>
              <string>app-store</string> <key>signingStyle</key>
              <string>automatic</string>
              <key>teamID</key>
              <string>${{ secrets.APPLE_TEAM_ID }}</string>
          </dict>
          </plist>
          EOF

      - name: Build IPA (iOS App)
        run: |
          flutter build ipa --release --export-options-plist=ios/ExportOptions.plist

      - name: Sauvegarder le fichier IPA (Artefact)
        uses: actions/upload-artifact@v4
        with:
          name: KartApp-iOS
          path: build/ios/ipa/*.ipa
